repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: trailing-whitespace

  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.60.2
    hooks:
      - id: golangci-lint

  - repo: https://github.com/semgrep/semgrep
    rev: v1.84.1
    hooks:
      - id: semgrep
